### ISSUE TITLE
Webhook is not working when the secret contains a `+` character

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#296] opened 2023-04-03 21:41 UTC
During testing it was noticed that Webhook validation functionality would intermittently not work during setup. 

With some dev help investigating @mickmister noticed the issue to occurs when the Mattermost webhook secret contains a `+` 

Follow-up testing seems to confirm this. No issues found with other special characters (`-` and `_` can also be included)
This would have also stopped the webhook deliveries until the admins tries gegenerating the secret.

This would **not** be a recent regression.     

Steps:
- Install Zoom and configure the authentication
- Click `regenerate` on the webhook secret again and again until the string contains a `+`
- Attempt to configure the webhook in Zoom with this secret

**Observed** Zoom App wizard will not validate the webhook

**Comment by avas27JTG** [comment] 2023-11-14 08:47
This is a bug in Mattermost that was also identified [earlier](https://github.com/mattermost/mattermost-plugin-azure-devops/pull/150#discussion_r1139959164) and has a JIRA ticket https://mattermost.atlassian.net/browse/MM-51451.

**Comment by mickmister** [comment] 2023-11-20 02:57
@avas27JTG I think we can close this as the core issue is fixed, and it sort of occurs by chance anyway. Thoughts? @avas27JTG @hanzei

**Comment by avas27JTG** [comment] 2023-11-20 07:13
> @avas27JTG I think we can close this as the core issue is fixed, and it sort of occurs by chance anyway. Thoughts? @avas27JTG @hanzei

@mickmister I'm not sure about `core issue is fixed` can you please mention what you mean by that? Also, I was able to reproduce this issue when `+` character was present in the generated secret.

**Comment by mickmister** [comment] 2023-11-20 15:57
> I'm not sure about "core issue is fixed" can you please mention what you mean by that?

@avas27JTG I was referring to the fact that the webapp no longer produces generated values with `+` in them as of about 7 months ago https://github.com/mattermost/mattermost/pull/22869. I haven't tested this personally but are you still experiencing the `+` showing up, with the updated webapp version?

For existing generated values that have `+`s in them, I think it's okay if those are broken since we haven't had any customers report an issue with this AFAIK

**Comment by avas27JTG** [comment] 2023-11-22 15:25
> > I'm not sure about "core issue is fixed" can you please mention what you mean by that?
> 
> @avas27JTG I was referring to the fact that the webapp no longer produces generated values with `+` in them as of about 7 months ago [mattermost/mattermost#22869](https://github.com/mattermost/mattermost/pull/22869). I haven't tested this personally but are you still experiencing the `+` showing up, with the updated webapp version?
> 
> For existing generated values that have `+`s in them, I think it's okay if those are broken since we haven't had any customers report an issue with this AFAIK

thanks for clarifying @mickmister its fixed in `master` but do we need to also fix in the plugin also in case if someone is running on an MM version different from the `master`?

**Comment by mickmister** [comment] 2023-11-22 16:59
@avas27JTG I don't think so. We would also want to look through all other plugins affected by this, and I don't think it's worth the trouble. @DHaussermann Thoughts on closing this, as imo this is solved via the fix in the webapp?

Note that the bug in the webapp was that we were only replacing one instance of the `+`, so the issue only occurs when the generated secret happened to have more than one `+`

**Comment by avas27JTG** [comment] 2023-12-14 13:30
Okay then should we close this issue? @mickmister @DHaussermann

**Closed** 2023-12-14 19:05 UTC
Labels: Type/Bug
