### ISSUE TITLE
Zoom Authentication shows invalid oAuth state on first attempt 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#252] opened 2022-02-14 15:22 UTC
There is an issue with Zoom authentication where the user will see `invalid OAuth user state` the first time they attempt to use the connection link when using oAuth.
On the other 2nd attempt the connection link seems to work. 
- This issue does **not** seem to occur when using the latest production release `v1.5.1`
- The issue does seem to occur in the `master` branch

Steps:
- Build zoom from `master` brach
- Ensure Enable oAuth is true
- Ensure Beta Account level oAuth is false 
- Add credential for valid user level oAuth app in Zoom
- Enable the plugin
- Open a new browser session and login for clear results (optional)
- Run the connect or start command 
- Click the connection link
**observed**: User sees oAuth error in new window after providing oauth credentials
- Click the connection link again
**observed** The user will connect 
<img width="215" alt="Screen Shot 2022-02-14 at 9 46 35 AM" src="https://user-images.githubusercontent.com/35588783/153892190-c360582b-8da1-4c31-8765-35b524d69904.png">

**Comment by larkox** [comment] 2022-02-14 17:46
@DHaussermann any chance there is any difference between using the `/zoom start` command, `/zoom connect` command and clicking the start meeting button?

**Comment by catalintomai** [comment] 2022-02-14 19:59
@sanjaydemansol - can you take a look into it - seems to be a regression from previous release - also blocks this week's Zoom plugin release.

**Comment by hanzei** [comment] 2022-02-15 13:27
cc @lufty-demansol

**Comment by mickmister** [comment] 2022-07-28 21:31
Fixed with https://github.com/mattermost/mattermost-plugin-zoom/pull/268

Reopened https://github.com/mattermost/mattermost-plugin-zoom/issues/239 and https://github.com/mattermost/mattermost-plugin-zoom/issues/235

**Closed by mickmister** 2022-07-28 21:31 UTC
Labels: Type/Bug
