### ISSUE TITLE
After link the account with zoom after some time randomly when i use /zoom start command then again its asking me to link the account.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-zoom#239] opened 2021-11-10 19:13 UTC
**i don't have fix steps to regenerate the issue but maybe the console logs will help you** 

https://user-images.githubusercontent.com/89907719/141178114-794363f6-3e2d-44c5-b4dc-eb87d4184d95.mp4

![Screenshot from 2021-11-10 18-04-36](https://user-images.githubusercontent.com/89907719/141178140-9f77cc0a-e5eb-4dd3-b1f3-84e5cc4529f5.png)
![Screenshot from 2021-11-10 18-24-09](https://user-images.githubusercontent.com/89907719/141178155-5eb9baba-5abd-4ce6-88df-57f0bff687a2.png)

**Comment by catalintomai** [comment] 2021-11-15 19:50
@dipak-demansol - can you try this scenario at different time intervals - see if there is a pattern?

**Comment by dipak-demansol** [comment] 2021-11-16 06:18
> @dipak-demansol - can you try this scenario at different time intervals - see if there is a pattern?

Sure.

**Comment by dipak-demansol** [comment] 2021-11-26 13:19
> @dipak-demansol - can you try this scenario at different time intervals - see if there is a pattern?

after 1 hour its again asking to link the account but still its not the issue that i was talking about, under 30 minutes the issues was generated but i tried to regenerate it again but its not regenerated, its generated after 1 Hour.

**Comment by dipak-demansol** [comment] 2021-11-29 13:24
catalintomai i found the steps, that's how i was facing the issue.
steps :- 1) use /zoom start command 
             2) after 1 hour in the same channel use same command as /zoom start and it should work and meeting should created successfully.
             3) go in the other channel and type /zoom start command and **now it will Not Work and give you the link to connect your account.**

but the command worked properly in the last channel where i created the meeting but in the other channel it not worked that's why i told that issue generated under 1 hour, and one more thing is that why its worked on the last channel and not worked on the new/other channel? because if its not working then it should not work for all channel, it cant work channel specific.

**Comment by dipak-demansol** [comment] 2021-11-29 13:53
re-added triage label, now re-pro steps added.

**Comment by catalintomai** [comment] 2021-11-29 20:02
@dipak-demansol  - Thanks for investigating it. Looks like a valid issue - can the dev team start looking into a fix?

**Comment by dipak-demansol** [comment] 2021-12-07 07:09
> @catalintomai i found the steps, that's how i was facing the issue. steps :- 1) use /zoom start command 2) after 1 hour in the same channel use same command as /zoom start and it should work and meeting should created successfully. 3) go in the other channel and type /zoom start command and **now it will Not Work and give you the link to connect your account.**
> 
> but the command worked properly in the last channel where i created the meeting but in the other channel it not worked that's why i told that issue generated under 1 hour, and one more thing is that why its worked on the last channel and not worked on the new/other channel? because if its not working then it should not work for all channel, it cant work channel specific.

more info about the re-pro steps, **after the 2nd step if the user again use the same command in the same channel then also the command will not work and user will get the same URL to link the zoom account.**

**Comment by hanzei** [comment] 2022-01-24 18:26
@sibasankarnayak Can we close this then as a duplicate of https://github.com/mattermost/mattermost-plugin-zoom/issues/235?

**Comment by raghavaggarwal2308** [comment] 2023-12-26 09:28
@mickmister

**Comment by raghavaggarwal2308** [comment] 2023-12-26 09:28
> @sibasankarnayak Can we close this then as a duplicate of https://github.com/mattermost/mattermost-plugin-zoom/issues/235?

@mickmister Can this issue be closed?

**Closed** 2024-01-04 04:08 UTC
Labels: Duplicate
